//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlayer_WCF.MusicServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MusicServiceReference.ItransferService")]
    public interface ItransferService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItransferService/GetPlaylist", ReplyAction="http://tempuri.org/ItransferService/GetPlaylistResponse")]
        string[] GetPlaylist();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItransferService/GetPlaylist", ReplyAction="http://tempuri.org/ItransferService/GetPlaylistResponse")]
        System.Threading.Tasks.Task<string[]> GetPlaylistAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItransferService/GetLargeObject", ReplyAction="http://tempuri.org/ItransferService/GetLargeObjectResponse")]
        System.IO.Stream GetLargeObject(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItransferService/GetLargeObject", ReplyAction="http://tempuri.org/ItransferService/GetLargeObjectResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetLargeObjectAsync(string filename);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ItransferServiceChannel : MusicPlayer_WCF.MusicServiceReference.ItransferService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItransferServiceClient : System.ServiceModel.ClientBase<MusicPlayer_WCF.MusicServiceReference.ItransferService>, MusicPlayer_WCF.MusicServiceReference.ItransferService {
        
        public ItransferServiceClient() {
        }
        
        public ItransferServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItransferServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItransferServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItransferServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetPlaylist() {
            return base.Channel.GetPlaylist();
        }
        
        public System.Threading.Tasks.Task<string[]> GetPlaylistAsync() {
            return base.Channel.GetPlaylistAsync();
        }
        
        public System.IO.Stream GetLargeObject(string filename) {
            return base.Channel.GetLargeObject(filename);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetLargeObjectAsync(string filename) {
            return base.Channel.GetLargeObjectAsync(filename);
        }
    }
}
